### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [AnonGuy/yapipenv.zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by jerbob** [comment]
Hey @unixorn, thanks for using my plugin!
I've added the MIT license to the project, so feel free to add this to the list :smile:
