### ISSUE TITLE
Can't remove virtualenv

### ISSUE THREAD

**Issue by tomyun** [AnonGuy/yapipenv.zsh#3]
When using this plugin, if I ran `pipenv --rm` in the directory managed by pipenv, it would fail.

```
$ pipenv --rm
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
You are attempting to remove a virtualenv that Pipenv did not create. Aborting.
Aborted!
```

**Comment by jerbob** [comment]
Thanks for bringing this to my attention @tomyun!

It looks like I wasn't setting the [`PIPENV_ACTIVE`](https://github.com/pypa/pipenv/blob/6c62d23cfcd1255b62bf7ef31b97caa5af492f46/pipenv/environments.py#L301) variable, which is what pipenv uses to ensure that it has activated the environment correctly.

 `pipenv --rm` should now work as expected:

<a href="https://asciinema.org/a/238977"><img src="https://asciinema.org/a/238977.png" width="836"/></a>
